### ISSUE TITLE
IDE project files checked in repo

### ISSUE THREAD

**Issue by vovkab** [googlesamples/android-JobScheduler#1]
1. it is bad practices to check in your ide related files
2. since you are using gradle, project can be easily recovered from build.gradle files.

**Comment by tjohns** [comment]
Thanks for the heads up. This was an error in our packaging script.

I'll get it fixed shortly.

**Comment by keyboardsurfer** [comment]
Fixed within 53986bd986359107d2cd1c3368259e03a9ba191a
