### ISSUE TITLE
Cancelling schedule was not working

### ISSUE THREAD

**Issue by vikramKirubaharan** [googlesamples/android-JobScheduler#14]
Steps to Reproduce
1. Set the work duration for 10 seconds
2. Click schedule job.
3. click finish last task button at 3 seconds. onstop task event will get triggered.
4. At 10th second also on stop task button will glow.
      This is because of calling sendMessage method within the run method of myjobservice class

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
