### ISSUE TITLE
Can JobScheduler  run on API level 18 or minimum API 21 is required?

### ISSUE THREAD

**Issue by bkjbkjbnkj687698698** [googlesamples/android-JobScheduler#2]

**Comment by keyboardsurfer** [comment]
[JobScheduler](https://developer.android.com/reference/android/app/job/JobScheduler.html) was introduced with API level 21 and not available in API level 18.

**Comment by bkjbkjbnkj687698698** [comment]
Is there any alternative of JobScheduler  for API less than 21?

**Comment by thagikura** [comment]
I believe there is no alternative for API less than 21 at this moment.
