### ISSUE TITLE
typo in Class description of Log.java

### ISSUE THREAD

**Issue by mTwTm** [googlesamples/android-JobScheduler#4]
`Most of the methods in this class server only to map a method call in Log to its equivalent in LogNode.`

IMO, `server` should actually be `serve`.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
