### ISSUE TITLE
JobScheduler start job not triggered.

### ISSUE THREAD

**Issue by vamshikhoslalabs** [googlesamples/android-JobScheduler#6]
Hi I have been using JobScheduler since 3months. Haven't faced any issue until yesterday. It seem there is a behaviour change in the way it works. Whenever i use `jobscheduler.schedule(jobinfo)` it used to trigger immediately but right now it take 5mins or more to trigger the Job Service. Can I know why is this happening?

```
jobInfo = new JobInfo.Builder(JOB_SERVICE_LOCATION_PROBE, new ComponentName(getApplicationContext(), LocationJob.class))
                                        .setBackoffCriteria(BACKGROUND_JOB_BACK_OFF, JobInfo.BACKOFF_POLICY_EXPONENTIAL)
                                        .setRequiredNetworkType(JobInfo.NETWORK_TYPE_ANY)
                                        .setExtras(persistableBundle).build();

jobscheduler.schedule(jobInfo);
```

**Comment by vamshikhoslalabs** [comment]
Can anyone comment on this?

**Comment by morphine9** [comment]
try setting setMinimumLatency(0) explicitly.

**Comment by ZeeRooo** [comment]
Since Marshmallow the minimum time is set to 5 mins by the system itself. But wait! in Nougat+ is 15mins, so this api only works if you want a very inexact task

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
