### ISSUE TITLE
when the reboot the system all the jobs are closed

### ISSUE THREAD

**Issue by arunpandian22** [googlesamples/android-JobScheduler#8]
After adding the jobs in job scheduler and reboot the system and open the app all pending jobs are cancelled. why?

**Comment by umerabidin** [comment]
while creating JobInfo object use  jobInfo.setPersisted(true), that allows the app to run on restart.
This is the permission when a job is created as RECEIVE_BOOT_COMPLETED works

**Comment by umerabidin** [comment]
hope this link will solve your problem:
http://www.zoftino.com/android-job-scheduler-example

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
