### ISSUE TITLE
gradlew build failed

### ISSUE THREAD

**Issue by hjy1210** [googlesamples/android-JobScheduler#9]
1. I execute gradlew build in root directory，got the following error message:
======
D:\Github\android-JobScheduler>gradlew build
Starting a Gradle Daemon, 3 stopped Daemons could not be reused, use --status for details

> Configure project :Application
Configuration 'compile' in project ':Application' is deprecated. Use 'implementation' instead.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':Application'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
=======

2. If I load project in android studio, after update, sync ..., also failed.

PS:My studio version is 3.2, java version is 10.0.2

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
